all: prolific generation explorer slug slugrace

prolific:
	gcc prolific.c -o prolific

generation:
	gcc generation.c -o generation

explorer:
	gcc explorer.c -o explorer

slug:
	gcc slug.c -o slug

slugrace:
	gcc slugrace.c -o slugrace


clean:
	rm -f prolific generation explorer slug slugrace
